"""add read_at to notifications

Revision ID: add_read_at_to_notifications
Revises: d80b86de5245
Create Date: 2026-07-24 09:40:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_read_at_to_notifications'
down_revision = 'd80b86de5245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite-safe additive migration for existing rows.
    op.execute("ALTER TABLE notifications ADD COLUMN read_at DATETIME")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('read_at')

    # ### end Alembic commands ###
