"""add collaboration lifecycle modules

Revision ID: d80b86de5245
Revises: 
Create Date: 2026-07-19 23:48:41.838690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd80b86de5245'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite-safe additive migration for existing rows.
    op.execute("ALTER TABLE projects ADD COLUMN review_status VARCHAR(20) NOT NULL DEFAULT 'pending'")
    op.execute("ALTER TABLE users ADD COLUMN is_supervisor BOOLEAN NOT NULL DEFAULT 0")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_supervisor')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('review_status')

    # ### end Alembic commands ###
